In [3]:
import numpy as np

a= np.array([20,30,40])
b= np.array([50,60,70])
print(a)
print(b)
print(a+b)

[20 30 40]
[50 60 70]
[ 70  90 110]


In [2]:
l1= [20,30,40]
l2= [50,60,70]
print(l1+l2)

[20, 30, 40, 50, 60, 70]


In [5]:
l1= [20,30,40]
print(l1)

[20, 30, 40]


In [7]:
l2=[70,80,90]
print(l2)

[70, 80, 90]


In [1]:
import  numpy as np 
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr)

[[10 20 30 40]
 [50 60 70 80]]


In [4]:
import  numpy as np 
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))

(2, 4)
8
2


In [11]:
a = [[10,20,30,40],[50,60,70,80]]
arr=np.array(a)
print(arr.shape)
print(arr.size)
print(len(arr))
print(arr.dtype)
print(arr.astype(int))

(2, 4)
8
2
int32
[[10 20 30 40]
 [50 60 70 80]]


mathematical functions

In [13]:
import numpy as np
arr1 = np.array([10,20,30,40])
arr2 = np.array([50,60,70,80])
print(arr1+arr2)
print(np.add(arr1,arr2))

[ 60  80 100 120]
[ 60  80 100 120]


In [15]:
import numpy as np
arr1 = np.array([[10,20],[30,40]])
arr2 = np.array([[50,60],[70,80]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[-40 -40]
 [-40 -40]]
[[-40 -40]
 [-40 -40]]


combining and splitting the arrays

In [17]:
# concatenate

arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])
print(np.concatenate([arr1,arr2]))


[10 20 30 40  1  2  3  4]


In [20]:
arr1 = np.array([[10,20],[30,40]])
arr2 = np.array([[1,2],[3,4]])
print(np.concatenate([arr1,arr2],axis=0))

[[10 20]
 [30 40]
 [ 1  2]
 [ 3  4]]


In [21]:
print(np.hstack([arr1,arr2]))

[[10 20  1  2]
 [30 40  3  4]]


In [22]:
print(np.vstack([arr1,arr2]))

[[10 20]
 [30 40]
 [ 1  2]
 [ 3  4]]


In [23]:
a = np.array([10,20,40,60,70,80])
print(np.array_split(a,3))

[array([10, 20]), array([40, 60]), array([70, 80])]


adding and removing arrays

In [24]:
import numpy as np

a= np.array([20,40,60,80])
print(np.append(a,90))

[20 40 60 80 90]


In [25]:
print(np.insert(a,1,50))

[20 50 40 60 80]


In [26]:
print(np.delete(a,1))

[20 60 80]


sort,filter and search

In [ ]:
# Sort
a = np.array([3,2,9,6,12,4])
print(np.sort(a))

[ 2  3  4  6  9 12]


In [28]:
# search
a = np.array([3,2,9,6,12,4])
s= np.where(a==2)
print(s)

(array([1], dtype=int64),)


In [35]:
# searchsorted
b = np.array([4,9,12,16,18])
ss = np.searchsorted(b,18)
print(ss)

4


In [ ]:
# filter
c= np.array([20,30,40,50])
t=[True,False,True,False]
new=c[t]
print(new)

[20 40]


In [38]:
c= np.array([20,30,40,50])
fa =c>35
new=c[fa]
print(new)

[40 50]


Aggregating functions in numpy

In [45]:
d= np.array([20,30,40,70])
print(np.sum(d))
print(np.min(d))
print(np.max(d))
print(np.size(d))
print(np.mean(d))
print(np.cumsum(d))
print(np.cumprod(d))

160
20
70
4
40.0
[ 20  50  90 160]
[     20     600   24000 1680000]


stastical functions in numpy

In [52]:
import numpy as np
import statistics as stat
baked_food = [200,300,150,280,270,175,280,300]
a=np.array(baked_food)
print(np.mean(baked_food))
print(np.median(baked_food))
print(stat.mode(baked_food))
print(np.std(baked_food))
print(np.var(baked_food))

244.375
275.0
300
55.98200045550355
3133.984375


In [53]:
# coreational coeficients

tobacco_consumption = [30,50,10,30,40,50]
deaths = [100,90,70,60,90,110]
print(np.corrcoef(tobacco_consumption,deaths))

[[1.         0.63745942]
 [0.63745942 1.        ]]


In [54]:
price = [110,140,170,200,300]
sales =[10,5,9,10,20]
print(np.corrcoef(price,sales))

[[1.         0.86152918]
 [0.86152918 1.        ]]
