In [2]:
import numpy as np

In [7]:
a = np.array([[1,2],[3,4]])

np.linalg.matrix_power(a,2)

array([[ 7, 10],
       [15, 22]])

In [8]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [9]:
np.linalg.matrix_power(a,3)

array([[ 37,  54],
       [ 81, 118]])

In [10]:
np.linalg.matrix_power(a,0)

array([[1, 0],
       [0, 1]])

In [11]:
np.linalg.matrix_power(a,-2)

array([[ 5.5 , -2.5 ],
       [-3.75,  1.75]])

In [13]:
b =np.linalg.inv(a)
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [14]:
np.linalg.matrix_power(b,2)

array([[ 5.5 , -2.5 ],
       [-3.75,  1.75]])