In [1]:
import numpy as np 

In [2]:
a = np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [3]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [4]:
a.flatten(order="F")

array([ 1,  4,  6,  9,  2,  5,  7, 10,  3,  6,  8, 11])

In [5]:
a.flatten(order="A")

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [7]:
c = np.array([[1,2],[3,4]])
c

array([[1, 2],
       [3, 4]])

In [8]:
c.flatten()

array([1, 2, 3, 4])

In [9]:
c.flatten(order="F")

array([1, 3, 2, 4])

In [10]:
# Ravel function

d= np.array([[10,20],[30,40]])
d

array([[10, 20],
       [30, 40]])

In [12]:
np.ravel(a)

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [14]:
np.ravel(d,order="F")

array([10, 30, 20, 40])

In [17]:
g = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
g

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [18]:
np.ravel(g,order="F")

array([ 1,  6,  4,  9,  2,  7,  5, 10,  3,  8,  6, 11])

In [19]:
g.ravel()

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])