In [5]:
import numpy as np

help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.

    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

        .. versionadded:: 1.

In [2]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
np.ones((5,),dtype=int)

array([1, 1, 1, 1, 1])

In [4]:
np.ones((2,1))

array([[1.],
       [1.]])

In [5]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, without initializing entries.

    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via thi

In [7]:
np.empty([2,2])

array([[2.12199579e-314, 1.10555981e-311],
       [3.95252517e-321, 3.79442416e-321]])

In [8]:
np.empty(6)

array([6.23042070e-307, 1.33512376e-306, 1.11261230e-306, 7.56577399e-307,
       9.34600963e-307, 1.05699581e-307])

In [6]:
np.empty([3,4],dtype="int")

array([[          0,           0,           0,           0],
       [          1,          65,          24,           0],
       [-1701635408,         458,           1,           0]])