In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [6]:
b[0][0]

1

In [8]:
b[0][1]

2

In [9]:
b[-2][-2]

1

In [10]:
b[1]

array([3, 4])

In [12]:
c = ([1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20],[21,22,23,24])
c

([1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12],
 [13, 14, 15, 16],
 [17, 18, 19, 20],
 [21, 22, 23, 24])

In [17]:
c[0] [0] [2]

TypeError: 'int' object is not subscriptable

In [15]:
d[-2] [-3] [-3]

NameError: name 'd' is not defined