In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a.shape

(10,)

In [4]:
b = np.reshape(a,(5,2))
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
b.shape

(5, 2)

In [6]:
c = np.reshape(b,(5,2),order="F")
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
d = np.arange(10)
s = d.reshape((2,5))
s

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
# Resize function

t = np.arange(10)
v = np.resize(t,(2,3))
v

array([[0, 1, 2],
       [3, 4, 5]])