In [1]:
import numpy as np

In [3]:
c= np.array([1,2,3,4,5,6,7,8,9,10])
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
c[4:9]

array([5, 6, 7, 8, 9])

In [6]:
c[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
x= np.array([[1,2],[3,4],[5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
x[1:,1:]

array([[4],
       [6]])

In [12]:
x[:,:]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
d[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [15]:
d[::,::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [18]:
# three dimensinal array
h= [[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]
e=np.array(h)
e

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [20]:
e[:,:,:1]

array([[[ 1],
        [ 5],
        [ 9]],

       [[13],
        [17],
        [21]]])

In [21]:
e[:,1:,::2]

array([[[ 5,  7],
        [ 9, 11]],

       [[17, 19],
        [21, 23]]])