In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])


In [3]:
# ADIITION OPERATION ON MATRIX
a+b

array([[11, 22],
       [33, 44]])

In [5]:
# MULTIPLICATION OPERATION ON MATRIX
a*b

array([[ 10,  40],
       [ 90, 160]])

In [6]:
a.dot(b)

array([[ 70, 100],
       [150, 220]])

In [7]:
# TRANSPOSE FUNCTION
G = np.array([[1,2,3],[4,5,6]])
G

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.transpose(G)

array([[1, 4],
       [2, 5],
       [3, 6]])