In [1]:
import numpy as np

help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is exc

In [2]:
np.linspace(2,3,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [6]:
np.linspace(2,3,num=5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [7]:
np.linspace(1,100,num=5,endpoint=False)

array([ 1. , 20.8, 40.6, 60.4, 80.2])

In [9]:
np.linspace(1,100,num=5,retstep=True)

(array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ]), 24.75)

In [11]:
np.linspace(1,100,num=5,dtype="int")

array([  1,  25,  50,  75, 100])