In [1]:
import numpy as np

In [2]:
a = np.matrix("1 2; 3 4")
a

matrix([[1, 2],
        [3, 4]])

In [3]:
b = np.matrix([[10,20],[30,40]])
b

matrix([[10, 20],
        [30, 40]])

In [4]:
 # Matix Addition operation

a+b

matrix([[11, 22],
        [33, 44]])

In [5]:
a*b

matrix([[ 70, 100],
        [150, 220]])

In [6]:
a.T

matrix([[1, 3],
        [2, 4]])