In [1]:
import numpy as np

In [3]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [4]:
# Method - 1 (change the datatype)
a.astype(int)

array([0, 0, 0])

In [5]:
# method 2

np.float64(a)

array([0., 0., 0.])