In [2]:
import numpy as np

In [8]:
a= np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
b = np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [6]:
c = np.array([10,20])
c

array([10, 20])

In [9]:
a+c

array([[11, 22],
       [13, 24],
       [15, 26]])