In [1]:
import numpy as np

In [2]:
# Transpose Function

a = np.arange(1,11).reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [3]:
np.transpose(a)

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [4]:
# operation on 3-D array

c = np.arange(1,25).reshape(2,3,4)
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [10]:
np.transpose(c)

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [11]:
np.transpose(c).shape

(4, 3, 2)

In [13]:
# trnspose on 1-D array

i= np.arange(1,10)
i

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.transpose(i)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:

v = np.arange(1,11).reshape(5,2)
v

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [16]:
np.transpose(v,axes=(1,0))

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [17]:
np.transpose(v,axes=(0,1))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [18]:
x = np.arange(1,25).reshape(2,3,4)
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [19]:
np.transpose(x,(1,2,0))

array([[[ 1, 13],
        [ 2, 14],
        [ 3, 15],
        [ 4, 16]],

       [[ 5, 17],
        [ 6, 18],
        [ 7, 19],
        [ 8, 20]],

       [[ 9, 21],
        [10, 22],
        [11, 23],
        [12, 24]]])

In [20]:
h= np.array([[1,2],[3,4]])
h

array([[1, 2],
       [3, 4]])

In [25]:
h.transpose()

array([[1, 3],
       [2, 4]])

In [26]:
h.T

array([[1, 3],
       [2, 4]])

In [28]:
np.swapaxes(h,0,1)

array([[1, 3],
       [2, 4]])

In [30]:
m= np.array([[1,2,3]])
m

array([[1, 2, 3]])

In [31]:
m.shape

(1, 3)

In [32]:
np.swapaxes(m,1,0)

array([[1],
       [2],
       [3]])

In [33]:
c = np.arange(1,25).reshape(2,3,4)
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [34]:
np.swapaxes(c,1,2)

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])

In [35]:
np.swapaxes(c,1,2).shape

(2, 4, 3)

In [36]:
c.swapaxes(1,2)

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])