In [1]:
import  numpy as np

In [3]:
a = np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [5]:
index = np.array([1,4,5])
a[index]

array([ 3,  9, 11])

In [6]:
c= np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
c[[0,2],[2,0]]

array([3, 7])

In [11]:
# Boolean indexing

g = np.array([[1,-2,3],[4,-2,3]])
g

array([[ 1, -2,  3],
       [ 4, -2,  3]])

In [12]:
g[g<0]

array([-2, -2])

In [13]:
g[g<0]*4

array([-8, -8])