In [2]:
import numpy as  np

In [6]:
a = np.arange(1,5)
b = np.arange(6)

f= np.concatenate((a,b))
f

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 5])

In [7]:

c = np.arange(4)
d =np.concatenate((a,b,c))
d

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3])

In [9]:
e = np.zeros(10)
g= np.concatenate((a,b),out=e)
g

array([1., 2., 3., 4., 0., 1., 2., 3., 4., 5.])

In [12]:
# concatenate operation on 2-D array

h = np.array([[1,2],[3,4]])
i = np.array([[5,6]])

j = np.concatenate((h,i))
j

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
z = np.concatenate((h,i.T),axis=1)
z

array([[1, 2, 5],
       [3, 4, 6]])

In [17]:
# Vstack fnction - for concatenation of two arrays

m = np.arange(6)
n = np.arange(5)
o = np.arange(5)
p = np.vstack((n,o))
p

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [18]:

h = np.array([[1,2],[3,4]])
i = np.array([[5,6]])

num =np.concatenate((h,i))
num

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
num2 = np.vstack((h,i))
num2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
# hStack function - for concatenating 2 arrays

m = np.arange(6)
n = np.arange(5)
o = np.arange(5)

t= np.hstack((m,n))
t

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4])

In [23]:

h = np.array([[1,2],[3,4]])
i = np.array([[5,6]])

w = np.hstack((h,i.T))
w

array([[1, 2, 5],
       [3, 4, 6]])

In [31]:
# split function - for split the array

d1 = np.arange(1,10)
np.split(d1,3)


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [32]:
d2 = np.arange(1,13).reshape(6,2)
d2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [33]:
np.split(d2,2)

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

In [35]:
np.vsplit(d2,2)

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]