In [1]:
import numpy as np

In [3]:
a = np.arange(1,34,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [4]:
# Addition operation

a+5

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [11]:
b = np.arange(1,34,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [12]:
a+b

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66])

In [14]:
a*b

array([   1,    9,   25,   49,   81,  121,  169,  225,  289,  361,  441,
        529,  625,  729,  841,  961, 1089])

In [17]:
c= np.array([[1,2,3],[4,5,6]])

c

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
d= np.array([[1,2,1],[2,1,1]])
d

array([[1, 2, 1],
       [2, 1, 1]])

In [19]:
c+d

array([[2, 4, 4],
       [6, 6, 7]])